global using static MFUtility.Extensions.BoolExtensions;
global using static MFUtility.Extensions.CollectionExtensions;
global using static MFUtility.Extensions.DateTimeExtensions;
global using static MFUtility.Extensions.DispatcherExtensions;
global using static MFUtility.Extensions.EnumExtensions;
global using static MFUtility.Extensions.FileExtensions;
global using static MFUtility.Extensions.FrameworkElementExtensions;
global using static MFUtility.Extensions.NumericExtensions;
global using static MFUtility.Extensions.PathExtensions;
global using static MFUtility.Extensions.ServiceProviderExtensions;
global using static MFUtility.Extensions.StringExtensions;
global using static MFUtility.Extensions.VisualExtensions;
global using static MFUtility.Helpers.AppHelper;
global using static MFUtility.Helpers.ConfigHelper;
global using static MFUtility.Helpers.EnumHelper;
global using static MFUtility.Helpers.ProcessHelper;
global using static MFUtility.Helpers.VisualHelper;
global using static MFUtility.Helpers.LogHelper;
global using static MFUtility.Helpers.ServiceHelper;
global using static MFUtility.Helpers.ReflectionHelper;
global using static MFUtility.Helpers.ResourceHelper;
global using static MFUtility.Services.NotificationService;
global using static MFUtility.Enums.NotificationMode;
global using static MFUtility.Enums.NotificationType;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Windows;
global using System.Windows.Controls;