global using static MFUtility.Extensions.VisualExtensions;
global using static MFUtility.Helpers.AppHelper;
global using static MFUtility.Helpers.ConfigHelper;
global using static MFUtility.Helpers.EnumHelper;
global using static MFUtility.Helpers.ProcessHelper;
global using static MFUtility.Helpers.VisualHelper;
global using static MFUtility.Helpers.LogHelper;
global using static MFUtility.Helpers.ServiceHelper;
global using static MFUtility.Helpers.ReflectionHelper;
global using static MFUtility.Helpers.ResourceHelper;
global using static MFUtility.Notifications.Services.NotificationService;
global using static MFUtility.Notifications.Services.ToastService;
global using static MFUtility.Notifications.Enums.NotificationMode;
global using static MFUtility.Notifications.Enums.NotificationType;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Windows;
global using System.Windows.Controls;